version: '3.2'
# Services block
services:
    app:
        container_name: ${APP_NAME}-app
        image: ghcr.io/kangketikonlen/${APP_NAME}:${DOCKER_IMAGE_VERSION}
        networks:
            - internal
        ports:
            - "${DOCKER_APP_PORT:-8000}:80"
        env_file:
            - .env
        environment:
            - "DB_HOST=${DOCKER_DATABASE_HOST}"
            - "DB_DATABASE=${DOCKER_DATABASE_NAME}"
            - "DB_USERNAME=${DOCKER_DATABASE_USERNAME}"
            - "DB_PASSWORD=${DOCKER_DATABASE_PASSWORD}"
        depends_on:
            - database
        volumes:
            - ./storage/app:/var/www/app/storage/app
            - ./storage/logs:/var/www/app/storage/logs
        restart: "always"
    database:
        container_name: ${APP_NAME}-database
        image: mariadb:10.5.9
        command: --max_allowed_packet=256M
        networks:
            - internal
        ports:
            - "${DOCKER_DATABASE_PORT}:3306"
        env_file:
            - .env
        environment:
            MYSQL_USER: '${DOCKER_DATABASE_USERNAME}'
            MYSQL_DATABASE: '${DOCKER_DATABASE_NAME}'
            MYSQL_PASSWORD: '${DOCKER_DATABASE_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: '${DOCKER_DATABASE_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./storage/database:/var/lib/mysql
        restart: "always"
    dbms:
        container_name: ${APP_NAME}-dbms
        image: phpmyadmin:5.2.0
        depends_on:
            - database
        networks:
            - internal
        ports:
            - "${DOCKER_DBMS_PORT}:80"
        environment:
            - "PMA_HOST=${APP_NAME}-database"
            - "UPLOAD_LIMIT=500M"
        restart: "always"
# Volumes block
volumes:
    storage:
        name: ${APP_NAME}-volume
# Networks block
networks:
    internal:
        name: ${APP_NAME}-network
