on:
  push:
    branches:
      - "testing"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

name: 🖥️ Sync to server
jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
    - name: 🐙 Git checkout
      uses: actions/checkout@v3

    - name: 📁 Make sure repository is latest
      run: git fetch --prune --unshallow

    - name: 🚀 Update server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.SERVER }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        connect_timeout: 120s
        first_ssh: |
          cd ${{ secrets.DIRECTORY }}
          bash run.sh
          exit
