on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

name: 🖥️ Sync to server
jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
    - name: 🐙 Git checkout
      uses: actions/checkout@v3

    - name: 📁 Make sure repository is latest
      run: git fetch --prune --unshallow

    - name: 🚀 Update server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.PROD_SERVER }}
        user: ${{ secrets.PROD_USERNAME }}
        pass: ${{ secrets.PROD_PASSWORD }}
        port: ${{ secrets.PROD_PORT }}
        connect_timeout: 120s
        first_ssh: |
          cd ${{ secrets.PROD_DIR }}
          sed -i "s/IMAGE_VERSION=.*/IMAGE_VERSION=${{ env.NEW_TAG }}/g" run.sh
          bash run.sh
