on:
  push:
    branches:
      - "version"

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

name: 🏷️ Assign new tag
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 🐙 Git checkout
      uses: actions/checkout@v3

    - name: 📁 Make sure repository is latest
      run: git fetch --prune --unshallow

    - name: 🔖 Create tag
      uses: kangketikonlen/base-tagging@main
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_TYPE: ${{ github.event.repository.owner.type }}
        REPO_OWNER: ${{ github.event.repository.owner.name }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PRESERVE_VERSION: 25
