on:
  push:
    branches:
      - "testing"

env:
  image_name: ${{ github.event.repository.name }}

name: 📜 Test, pack & ship!
jobs:
  build:
    name: 📦 Build the app
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{steps.push-image.outputs.version}}

    steps:
    - name: 🐙 Git checkout
      uses: actions/checkout@v3

    - name: 📁 Make sure repository is latest
      run: git fetch --prune --unshallow

    - id: push-image
      name: 🛳️ Push image
      run: |
        image_id=ghcr.io/${{ github.repository_owner }}/$image_name
        image_id=$(echo $image_id | tr '[A-Z]' '[a-z]')
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        latest_tag=$(echo $latest_tag | sed -e 's/^v//')
        echo image_id=$image_id
        echo latest_tag=$latest_tag
        echo "version=$latest_tag" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    name: 🖥️ Upload to server
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
    - name: 🐙 Git checkout
      uses: actions/checkout@v3

    - name: 📁 Make sure repository is latest
      run: git fetch --prune --unshallow

    - name: 🚀 Update server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.SERVER }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        connect_timeout: 120s
        first_ssh: |
          cd ${{ secrets.DIRECTORY }}
          sed -i "s/IMAGE_VERSION=.*/IMAGE_VERSION=${{ needs.build.outputs.latest_version }}/g" run.sh
          bash run.sh
