on:
  push:
    branches:
      - "*"
      - "!main"
      - "!stable"

name: 🚀 CI Test Workflow
jobs:
  setup:
    name: 🛠️ Set Up
    runs-on: ubuntu-latest
    steps:
      - name: 🐙 Git checkout
        uses: actions/checkout@v3
      - name: 📁 Make sure repository is latest
        run: git fetch --prune --unshallow
      - name: 🛠️ Install dependencies
        run: composer install --no-interaction
      - name: 📦 Create vendor archive
        run: zip -r vendor.zip vendor
      - name: 📦 Upload vendor folder
        uses: actions/upload-artifact@v2
        with:
          name: vendor
          path: vendor.zip
  phpstan:
    needs: setup
    name: 🚦 PHPStan analysis
    runs-on: ubuntu-latest
    steps:
      - name: 🐙 Git checkout
        uses: actions/checkout@v3
      - name: 📦 Download vendor folder
        uses: actions/download-artifact@v2
        with:
          name: vendor
      - name: 📦 Extract vendor archive
        run: unzip vendor.zip
      - name: 🚦 Analyze with PHPStan
        run: composer phpstan
