on:
  push:
    branches:
      - "*"
      - "!main"
      - "!stable"

env:
  image_name: ${{ github.event.repository.name }}

name: 🚀 CI Test Workflow
jobs:
  setup:
    name: 🛠️ Set Up
    runs-on: ubuntu-latest
    steps:
      - name: 🐙 Git checkout
        uses: actions/checkout@v3

      - name: 📁 Make sure repository is latest
        run: git fetch --prune --unshallow

      - name: 📑 Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: ⏳ Install dependencies
        run: composer install --no-interaction

      - name: 📄 Create environment
        run: cp .env.example .env

      - name: 🔑 Generate app key
        run: php artisan key:generate

      - name: 💽 Set up database
        run: php artisan migrate --seed --env=testing

      - name: 🗺️ Check routes
        run: php artisan route:clear && php artisan route:list

  test:
    name: ✅ Run Tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Run php tests
        run: vendor/bin/phpunit

  phpstan:
    name: 🚦 PHPStan Analysis
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Install PHPStan
        run: composer require --dev phpstan/phpstan

      - name: 🚦 Analyze with PHPStan
        run: vendor/bin/phpstan analyze

      - name: 🛑 Stop workflow on PHPStan error
        if: ${{ failure() }}
        run: exit 1
