on:
  push:
    branches:
      - "*"
      - "!main"
      - "!stable"

name: 🚀 CI Test Workflow
jobs:
  phpstan:
    name: 🚦 PHPStan analysis
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Install dependencies
        run: composer install --no-interaction

      - name: 🚦 Analyze with PHPStan
        run: composer phpstan

      - name: 🛑 Stop workflow on PHPStan error
        if: ${{ failure() }}
        run: exit 1
