on:
  push:
    branches:
      - "*"
      - "!main"
      - "!stable"

name: 📜 Tests App
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testing
          MYSQL_DATABASE: larapulse
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: 🐙 Git checkout
        uses: actions/checkout@v3

      - name: 📁 Make sure repository is latest
        run: git fetch --prune --unshallow

      - name: 📑 Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: ⏳ Install dependencies
        run: composer install --no-interaction

      - name: 📄 Create environment
        run: cp .env.example .env

      - name: 🔑 Generate app key
        run: php artisan key:generate

      - name: 💽 Set up database
        run: php artisan migrate --seed --env=testing

      - name: 🗺️ Check routes
        run: php artisan route:clear && php artisan route:list

      - name: ✅ Run tests
        run: vendor/bin/phpunit
