on:
  push:
    branches:
      - "testing"

name: 🎯 Just testing
jobs:
  setup:
    name: 🖥️ Upload to server
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: 🐙 Git checkout
      uses: actions/checkout@v3
    - name: 📁 Make sure repository is latest
      run: git fetch --prune --unshallow
    - name: 🚀 Update server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.SERVER }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        connect_timeout: 120s
        scp: |
          '.docker/server/bin' => ${{ secrets.DIRECTORY }}
          '.docker/server/docker-compose.yml' => ${{ secrets.DIRECTORY }}
          '.docker/server/run.sh' => ${{ secrets.DIRECTORY }}
        last_ssh: |
          cd ${{ secrets.DIRECTORY }}
          bash run.sh
